/**
 * Rotating taglines for the Kekere login/signup hero. One is picked at
 * random per page load (see src/app/login/page.tsx) so returning visitors
 * see something different each time instead of the same fixed line.
 */
export const KEKERE_LOGIN_QUOTES: readonly string[] = [
  // Reading-lifestyle, in the spirit of the original line
  "Read in the time it takes to wait for a bus.",
  "Long enough to matter, short enough to finish before your food gets cold.",
  "A whole world before your data bundle runs out.",
  "Shorter than the queue at the bank. Better than the wait.",
  "Start on the bike, finish before the next stop.",
  "One story, one traffic jam. Choose the story.",
  "Finish it before NEPA takes the light.",
  "Short enough for a lunch break, good enough to ruin your whole day.",
  "The kind of story you can finish before your battery starts worrying you.",
  "Perfect for the length of a bad Nollywood ad break.",
  "Long enough for the generator to run out of fuel. Short enough to still be worth it.",
  "Made for the exact length of your network buffering.",
  "Shorter than the aunty's phone call that was 'just two minutes.'",
  "The kind of story that survives even 1% battery.",
  "Perfect for the wait between 'the food is almost ready' and actual food.",
  "Read one before your data runs out. Read another after you top up.",
  "Built for commutes, queues, and situations only Lagos understands.",
  "Great for the wait at the barber's. Less great for missing your turn.",
  "Short enough to read standing in a moving bus. We don't recommend it. We understand it.",
  "You can read this before your ride-hailing driver cancels on you.",
  "This story is shorter than the apology you're owed.",
  "Read it before the power goes. Finish it before it comes back.",

  // Funny one-liners
  "Not every hero wears a cape. Some just finish their manuscripts.",
  "Warning: may cause you to miss your bus stop.",
  "Written by humans. Occasionally edited by caffeine.",
  "If you finish this in one sitting, congratulations — you have a functioning attention span.",
  "Reading: the original doom-scrolling.",
  "This app was built by people who also stayed up till 2am for 'just one more chapter.'",
  "We promise these stories are shorter than your ex's paragraph texts.",
  "Some people collect stamps. We collect endings that hit different.",
  "No plot twist here — just the honest truth that short stories slap.",
  "Five minutes well spent. Unlike most meetings.",
  "This app has more plot twists than your family WhatsApp group.",
  "We made an app so good you'll forget to check your other app.",
  "No, we won't tell you how the story ends. Yes, we know you'll peek anyway.",
  "Downloaded for the stories. Stayed for the cowries.",
  "This is the only queue you'll ever enjoy standing in.",
  "We built a whole app around 'just five more minutes.'",
  "The stories are short. The withdrawal process is not (we're working on it).",
  "An app built entirely on the premise that everyone is secretly waiting for something.",
  "Somewhere, someone just DNF'd a book you loved. We forgive them. Barely.",
  "The real plot twist is that you have three unread books and still opened this app.",
  "If the story made you text someone at 1am, it worked.",
  "A story this short has no room for filler. Every word had to earn its seat.",

  // Reader jokes
  "Readers: we judge books by their covers, then lie about it.",
  "A reader's to-be-read pile is just a very polite hostage situation.",
  "Nothing bonds two readers faster than mutually hating a bestseller.",
  "Some readers finish a book a week. Some readers finish a bookmark a year. No judgment.",
  "The five stages of finishing a good book: joy, grief, denial, Googling fan theories, buying the sequel out of spite.",
  "Readers don't skip pages. Readers 'strategically preview.'",
  "A reader's biggest lie: 'I'll just read one chapter before bed.'",
  "Real ones know the twist is coming. We warned you anyway.",
  "Every reader has a friend who 'doesn't really read' but has strong opinions on the ending.",
  "Show us a reader who's never cried in public over a book and we'll show you a liar.",
  "Readers: the only people who get personally offended on behalf of fictional characters.",
  "A good book ruins your sleep schedule and your social calendar. Equally.",
  "Readers don't retire a book. The book retires the reader.",
  "You haven't lived until a stranger asks 'is it good?' mid-cry on a bus.",
  "Every reader has skipped ahead to make sure a character survives. No shame.",
  "Some readers highlight quotes. Some readers just scream internally. Both valid.",
  "The most dangerous words in reading: 'let me just check the next chapter title.'",
  "Readers will defend a fictional villain with more passion than they defend themselves in arguments.",
  "A reader's bookshelf is 20% books they loved, 80% guilt.",

  // Writer jokes
  "Writers: professionally making up problems for people who don't exist.",
  "A writer's outline is a suggestion. To themselves. That they ignore.",
  "Every writer has three unfinished stories and one great excuse.",
  "Writers don't procrastinate. We 'gather material.'",
  "The first draft is where a writer lies to themselves for free.",
  "Writer's block: when your characters unionize and refuse to talk to you.",
  "Every writer secretly believes their villain makes the most sense in the room.",
  "A writer's search history could get them arrested or applauded. Rarely in between.",
  "Writers cry at their own plot twists. We warned them. We are them.",
  "The bravest thing a writer does isn't finishing the story. It's hitting publish.",
  "Writers: turning heartbreak into royalties since forever.",
  "Every writer has argued with a character who doesn't exist. And lost.",
  "A writer's playlist for 'the sad scene' has 47 songs and zero focus.",
  "Writers don't kill characters. Characters make choices. Bad ones. On purpose. By the writer.",
  "Some writers outline everything. Some writers find out the ending with the reader. Both are valid. One is chaos.",
  "A writer's most-used sentence: 'it made sense in my head.'",
  "Writing is easy. You just stare at a page until your doubts bleed.",
  "Every writer has renamed a character four times and still isn't sure.",

  // Book & publishing jokes
  "A book is just a very patient way to change someone's mind.",
  "The best recommendations come with a warning: 'don't start this on a work night.'",
  "Every classic was once somebody's risky idea.",
  "A cliffhanger is an author's love letter to your anxiety.",
  "Behind every good book is an editor who deleted the author's favorite line.",
  "Every bestseller was rejected by someone with very confident opinions.",
  "A book cover judges you back.",
  "Great endings are rare. Great excuses for bad endings are common.",
  "Somewhere, a debut writer just got their first 'no.' Somewhere else, they kept going anyway.",
  "A good title does half the work. A great first line does the rest.",
  "Publishing is just a very long game of 'trust me, bro' — until it isn't.",

  // Unpopular opinions about the literary world and reading culture
  "The short story is harder to write than the novel. Fight us.",
  "Most plot twists are just poor pacing wearing a costume.",
  "Nobody actually finished that 900-page fantasy series. We see you.",
  "A good ending is worth more than a slow beginning.",
  "Writer's block is just your brain asking for a nap.",
  "The sequel is rarely better. We said what we said.",
  "Not every story needs a moral. Some just need an ending.",
  "A great first line matters more than a great cover.",
  "Audiobooks count. Fight us again.",
  "The footnotes were never necessary.",
  "Prologues are usually a warning sign.",
  "A book doesn't need to be long to be literary.",
  "'It gets good after chapter five' is not a selling point.",
  "Some classics survived on reputation, not merit.",
  "Rereading counts as reading. So does listening.",
  "Not finishing a bad book is a personality strength.",
  "A twist you saw coming is still a good twist if it's earned.",
  "Short stories deserve their own shelf, not a footnote.",
  "The moral of the story shouldn't need explaining.",
  "Some authors should trust their readers more.",
  "A boring middle can ruin a great beginning and a great ending.",
  "Not every love interest deserves a redemption arc.",
  "Some book club picks are just homework with wine.",
  "'Everyone should read this' usually means 'I need someone to discuss my feelings with.'",
  "Page count is not a personality trait.",
  "The movie is sometimes just fine, actually.",
  "Writers are allowed to kill off your favorite. That's the job.",
  "An epilogue should answer questions, not raise new ones.",
  "A story doesn't need a villain to have stakes.",
  "'Critically acclaimed' and 'enjoyable' are not always the same thing.",
  "Some love triangles exist purely to pad the word count.",
  "A happy ending isn't lazy writing. It's a choice.",
  "Nobody needs a 200-page appendix. Somebody, tell them.",
  "The best world-building shows, doesn't explain.",
  "DNF-ing a book is self-care, not defeat.",

  // Smart brand copy
  "Small stories. Big feelings.",
  "Kekere means small. The stories don't stay that way.",
  "Every stall has a spirit. Every writer has a story.",
  "Good fiction doesn't need 400 pages to break your heart.",
  "We publish stories, not doorstops.",
  "The best plot twists happen in fewer words than you'd think.",
  "Some stories take a lifetime to write and five minutes to read. That's the magic.",
  "African stories. No passport required.",
  "A library that fits in your pocket and your commute.",
  "Real writers. Real readers. Real cowries.",
  "This is the shortest commitment you'll make all week.",
  "Written in Lagos, Accra, Nairobi, and everywhere in between.",
  "The bus will come. The story will end first.",
  "Great fiction has no size requirement. Neither do great writers.",
  "Somewhere, a writer just got a cowrie richer because you read this.",
  "New voices. Old truths. Short reads.",
  "We built this for the in-between moments — because that's most of life.",
  "Small enough to start on a whim. Good enough to finish on purpose.",
  "Not everything needs a sequel. Some things just need to be good once.",
  "Big stories don't need big page counts. They need good writers.",
] as const;

export function getRandomKekereLoginQuote(): string {
  return KEKERE_LOGIN_QUOTES[Math.floor(Math.random() * KEKERE_LOGIN_QUOTES.length)];
}
